# This is a basic workflow to help you get started with Actions

name: Dayli rebuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '00 06 * * *' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: { ref: main }

      # Runs a single command using the runners shell
      - name: Deploy to Netlify
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ff823951449a894921f76b9
