# This is a basic workflow to help you get started with Actions

name: Daily rebuild

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      #         with:
      #           repository: adamdjbrett/relcfp
      #           token: ${{ secrets.RELCFPCHRONJOB }}

      - name: Make executeable
        run: chmod +x ./get_rss.sh
      # Runs a single command using the runners shell
      - name: Get RSS
        run: ./get_rss.sh
      - name: Add & Commit
        uses: EndBug/add-and-commit@main
        with:
          add: feed.xml
      - name: Use Github App
        uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict
      - name: Data Format Converter Action
        shell: python
        id: xml2json
        run: |
          import xmltodict
          import json
          def validate_json(json_string):
            try:
                json.loads(json_string)
                return True
            except ValueError as e:
                print(f"Invalid JSON: {e}")
                return False
          with open('feed.xml', 'r') as xml_file:
              xml_data = xml_file.read()
              xml_dict = xmltodict.parse(xml_data)
              json_data = json.dumps(xml_dict, indent=4)
              with open('feed.json', 'w') as json_file:
                  json_file.write(json_data) 
      - name: Print result
        run: echo '$RESULT' > feed.json
        env:
          RESULT: ${{ steps.xml2json.outputs.output }}
      - name: Configure Git
        run: |
          git config --global user.name 'adamdjbrett'
          git config --global user.email '22662978+adamdjbrett@users.noreply.github.com'
      - name: Commit and push changes
        run: |
          git add 'feed.json'
          git commit -m 'Save output to file'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  
      - name: Deploy to Netlify
        uses: lwojcik/github-action-deploy-static-site@v1
        with:
          platform: netlify
          netlify_deploy_hook_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
          always_deploy: true
