name: Daily rebuild
on:
  schedule:
    - cron: 0 7,13 * * *
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict requests
      - name: Pagefind Install
        id: install
        run: python3 -m pip install 'pagefind[extended]'
      - name: Get RSS
        id: check
        run: python get_rss.py
      - name: Add & Commit
        if: steps.check.outputs.content_changed == 'true'
        uses: EndBug/add-and-commit@main
        with:
          add: feed.xml
      - name: Use Github App
        uses: actions/create-github-app-token@v1
        if: steps.check.outputs.content_changed == 'true'
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Print result
        if: steps.check.outputs.content_changed == 'true'
        run: cat _data/feed.json
      - name: Configure Git
        if: steps.check.outputs.content_changed == 'true'
        run: >
          git config --global user.name 'adamdjbrett'

          git config --global user.email '22662978+adamdjbrett@users.noreply.github.com'
      - name: Commit and push changes
        if: steps.check.outputs.content_changed == 'true'
        run: |
          git add _data/feed.json
          git commit -m 'Save output to file'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: jekyll-deploy
        uses: DavidS/jekyll-deploy@1.1.1
        with: null
        build-only: true
      - name: Pagefind Serve
        id: index
        run: python3 -m pagefind --site _site --serve
      - name: Deploy to Netlify
        uses: lwojcik/github-action-deploy-static-site@v1
        if: steps.check.outputs.content_changed == 'true'
        with:
          platform: netlify
          netlify_deploy_hook_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
          always_deploy: true
