name: YAML to JSON
run-name: ${{ github.actor }} YAML2JSON
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Data Format Converter Action
        uses: fabasoad/data-format-converter-action@v0
        id: xml2yaml
        with:
          input: "person.xml"
          from: "xml"
          to: "yml"
      - name: Print result
        run: echo "${{ steps.xml2yaml.outputs.output }}"