name: YAML to JSON
run-name: ${{ github.actor }} YAML2JSON
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Data Format Converter Action
        uses: fabasoad/data-format-converter-action@v0.2.3
        id: xml2json
        with:
          input: "authors.yml"
          from: "yml"
          to: "json"
      - name: Print result
        run: echo "${{ steps.xml2json.outputs.output }}"